export const SET_LOGINED = 'SET_LOGINED'

export const REMOVE_LOGINED = 'REMOVE_LOGINED'

export const SET_USER = 'SET_USER'

export const ADD_TAB = 'ADD_TAB'

export const ADD_MENU_TAB = 'ADD_MENU_TAB'

export const REMOVE_TAB = 'REMOVE_TAB'

export const SET_DEFAULT_ACTIVE_TAB = 'SET_DEFAULT_ACTIVE_TAB'

export const ADD_READED_MESSAGE = 'ADD_READED_MESSAGE'

export const REMOVE_UNREAD_MESSAGE = 'REMOVE_UNREAD_MESSAGE'

export const ADD_UNREAD_MESSAGE = 'ADD_UNREAD_MESSAGE'

export const SET_SIDEBAR_LIST = 'SET_SIDEBAR_LIST'

export const SET_STOP_TIME = 'SET_STOP_TIME'

export const SET_USER_AUTHS = 'SET_USER_AUTHS'
